Update utils.h to enable installation from source,
#define CHECK_LT(a, b) CHECK((a) < (b)) 
It's a workaround to allow for installing pytorch_sparse from source files. 
Missing definition leads to error while running pip install for the package:

    In file included from csrc/cpu/relabel_cpu.cpp:3:
    csrc/cpu/utils.h: In function 'int64_t uniform_randint(int64_t, int64_t)':
    csrc/cpu/utils.h:40:3: error: 'CHECK_LT' was not declared in this scope; did you mean 'CHECK'?
       40 |   CHECK_LT(low, high);
          |   ^~~~~~~~
          |   CHECK
    error: command '/root/anaconda3/envs/pyg/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

A complete final solution shall include #include <glog/logging.h>. Right now including <glog/logging.h> and installing pytorch with USE_GLOG=ON leads to errors with:
OSError: /root/pytorch_installation/pytorch_sparse/torch_sparse/_sample_cpu.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder7ForVar2Ev
The problem needs further investigation.